#!/usr/bin/env python3
"""Check and register the Extella MCP connection for Claude Code.

    python3 extella_connect.py            # doctor: what is connected, proven how
    python3 extella_connect.py --json     # the same, machine-readable
    python3 extella_connect.py register   # connect this machine's Extella account
    python3 extella_connect.py --selftest # offline checks, no network

WHY A SCRIPT. Three things lie about an Extella connection, all measured:
  * `claude mcp list` prints "✓ Connected" with no key and with a wrong key —
    MCP `initialize` answers HTTP 200 alike in all three cases;
  * a tool call without X-Agent-Id answers HTTP 200 with isError and
    "Failed to resolve dependency 'token'", blaming a key that is fine;
  * the same text comes back for a wrong key.
The truth comes from two places: `POST /api/token/validate` (is the key valid,
and which agent it belongs to) and a real MCP `tools/call` with the headers the
client will send.

SAME FORMAT AS THE BRIDGE. `register` writes exactly what
scripts/extella-mcp-accounts.mjs describes — one connection per account, a
derived handle, a 0600 token file, a 0700 headers helper, the server entry with
an absolute helper path. A parity test in the Codex plugin's suite compares the
two implementations, so they cannot drift apart silently.

Nothing here prints a key. Standard library only.
"""
import hashlib
import json
import os
import pathlib
import re
import shutil
import subprocess
import sys
import urllib.error
import urllib.request

MCP_URL = "https://api.extella.ai/mcp/"
VALIDATE_URL = "https://api.extella.ai/api/token/validate"
PROFILE = "default"
HANDLE_RE = re.compile(r"^acct_[a-f0-9]{12}$")
AGENT_RE = re.compile(r"^agent_[A-Za-z0-9_-]{8,128}$")
NO_KEY = ("No Extella key on this computer. One human action: in the Extella app open "
          "Library → System → Tokens, create a token and save it to "
          "~/.extella/api_token.txt with mode 600. Never paste the key into a chat.")


def home() -> pathlib.Path:
    return pathlib.Path(os.environ.get("HOME") or pathlib.Path.home())


# ── the bridge's format ────────────────────────────────────────────────────
def account_handle(token: str) -> str:
    digest = hashlib.sha256(f"extella-mcp-account-v1.{token.strip()}".encode("utf-8"))
    return "acct_" + digest.hexdigest()[:12]


def server_name(handle: str) -> str:
    assert HANDLE_RE.match(handle), "invalid handle"
    return f"extella_{handle}"


def token_file(handle: str, h: pathlib.Path) -> pathlib.Path:
    return h / ".extella" / "mcp" / f"{handle}.token"


def helper_file(handle: str, h: pathlib.Path) -> pathlib.Path:
    return h / ".extella" / "mcp" / f"{handle}.sh"


def helper_script(handle: str, agent_id: str, h: pathlib.Path) -> str:
    """Byte-for-byte what headersHelperScript() in the Node library produces."""
    if not AGENT_RE.match(agent_id or ""):
        raise ValueError("A resolved Extella agent id is required")
    return "\n".join([
        "#!/bin/sh",
        "# Generated by the Extella Claude bridge. Reads a 0600 token file.",
        "printf '{\"X-Auth-Token\":\"%s\",\"X-Profile-Id\":\"" + PROFILE +
        "\",\"X-Agent-Id\":\"" + agent_id + "\"}\\n' \\",
        f"  \"$(cat \"{token_file(handle, h)}\")\"",
        "",
    ])


def server_entry(helper_path: str) -> dict:
    return {"type": "http", "url": MCP_URL, "headersHelper": helper_path}


# ── keys and servers on this machine ───────────────────────────────────────
def keys_on_disk() -> list[tuple[str, str]]:
    """(where, value) for every distinct key the machine holds. Value never printed."""
    h, found, seen = home(), [], set()

    def add(where, value):
        value = (value or "").strip()
        if len(value) >= 8 and value not in seen:
            seen.add(value)
            found.append((where, value))

    add("EXTELLA_API_TOKEN", os.environ.get("EXTELLA_API_TOKEN"))
    for name in ("api_token.txt", "os_token.txt"):
        try:
            add(f"~/.extella/{name}", (h / ".extella" / name).read_text(encoding="utf-8"))
        except OSError:
            pass
    for f in sorted((h / ".extella" / "mcp").glob("acct_*.token")):
        try:
            add(f"~/.extella/mcp/{f.name}", f.read_text(encoding="utf-8"))
        except OSError:
            pass
    return found


def extella_servers() -> list[dict]:
    """Every Extella MCP server Claude Code knows, user and project scope."""
    try:
        cfg = json.loads((home() / ".claude.json").read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return []
    scopes = [("user", cfg.get("mcpServers") or {})]
    for path, project in (cfg.get("projects") or {}).items():
        scopes.append((f"project {path}", (project or {}).get("mcpServers") or {}))
    out = []
    for scope, servers in scopes:
        for name, entry in servers.items():
            if isinstance(entry, dict) and "api.extella.ai/mcp" in str(entry.get("url", "")):
                out.append({"name": name, "scope": scope, "entry": entry})
    return out


def server_headers(entry: dict) -> tuple[dict, str]:
    """Headers the client would send, and how they are stored."""
    helper = entry.get("headersHelper")
    if helper:
        if sys.platform.startswith("win"):
            return {}, "helper is a shell script — cannot run on native Windows"
        try:
            done = subprocess.run([helper], capture_output=True, text=True, timeout=30)
            return json.loads(done.stdout or "{}"), "helper"
        except (OSError, ValueError, subprocess.TimeoutExpired) as e:
            return {}, f"helper failed: {type(e).__name__}"
    return dict(entry.get("headers") or {}), "static headers in ~/.claude.json"


# ── proofs ─────────────────────────────────────────────────────────────────
def validate(token: str) -> dict:
    body = json.dumps({"token": token}).encode()
    req = urllib.request.Request(VALIDATE_URL, data=body, method="POST", headers={
        "Content-Type": "application/json", "X-Auth-Token": token, "X-Profile-Id": PROFILE})
    try:
        with urllib.request.urlopen(req, timeout=40) as r:
            data = json.loads(r.read().decode("utf-8", "replace"))
    except urllib.error.HTTPError as e:
        return {"valid": False, "why": f"HTTP {e.code}"}
    except Exception as e:                                       # noqa: BLE001
        return {"valid": None, "why": f"no answer ({type(e).__name__})"}
    return {"valid": bool(data.get("valid")), "agent_id": data.get("agent_id"),
            "why": "" if data.get("valid") else "token/validate: valid=false"}


def _mcp(body: dict, headers: dict, session: str = ""):
    h = {"Content-Type": "application/json", "Accept": "application/json, text/event-stream"}
    h.update(headers)
    if session:
        h["Mcp-Session-Id"] = session
    req = urllib.request.Request(MCP_URL, data=json.dumps(body).encode(), method="POST", headers=h)
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read(600_000).decode("utf-8", "replace"), r.headers.get("Mcp-Session-Id") or ""


def _last_json(text: str):
    last = None
    for line in text.splitlines():
        line = line.strip()
        line = line[5:].strip() if line.startswith("data:") else line
        if line.startswith("{"):
            try:
                last = json.loads(line)
            except ValueError:
                pass
    return last


# The proof tool. Chosen by measurement (30.09.2026), not by habit:
#   * list_profiles — rejects a wrong key (isError, "dependency 'token'") and answers a
#     valid one in ~600 characters: a real proof that fits any client's output limit;
#   * list_agents — also checks the key, but on a large account answers ~270 000
#     characters: it overflows the client's tool-output limit and, read partially,
#     cannot be parsed — which an absence-of-error check would call a success;
#   * get_current_profile_and_agent — answers "successfully" to a WRONG key: it echoes
#     the headers it was sent. Never a proof.
PROOF_TOOL = "list_profiles"


def prove_tool_call(headers: dict) -> tuple[bool, str]:
    """A real tools/call — the only thing that proves the MCP channel. Proven means a
    PARSED answer that says isError=false and carries content; anything else is not."""
    if not headers.get("X-Auth-Token"):
        return False, "no key in the headers"
    if not str(headers.get("X-Agent-Id", "")).strip():
        return False, "no X-Agent-Id: every tool call will fail and blame the key"
    try:
        _, sess = _mcp({"jsonrpc": "2.0", "id": 1, "method": "initialize", "params": {
            "protocolVersion": "2024-11-05", "capabilities": {},
            "clientInfo": {"name": "extella-connect", "version": "1"}}}, headers)
        text, _ = _mcp({"jsonrpc": "2.0", "id": 2, "method": "tools/call",
                        "params": {"name": PROOF_TOOL, "arguments": {}}}, headers, sess)
    except Exception as e:                                       # noqa: BLE001
        return False, f"MCP did not answer ({type(e).__name__})"
    return judge(_last_json(text))


def judge(answer) -> tuple[bool, str]:
    """Positive evidence only. An unparsed or empty answer is NOT a success."""
    if not isinstance(answer, dict):
        return False, "the tool answer could not be parsed — not proven"
    if "error" in answer:
        return False, "MCP refused the tool call"
    result = answer.get("result")
    if not isinstance(result, dict):
        return False, "no result in the tool answer — not proven"
    if result.get("isError") is not False:
        return False, "MCP refused the tool call"
    content = result.get("content") or []
    if not content or not str(content[0].get("text", "")).strip():
        return False, "the tool answered with nothing — not proven"
    return True, f"{PROOF_TOOL} answered with account data"


# ── doctor and register ────────────────────────────────────────────────────
def doctor() -> dict:
    report = {"accounts": [], "servers": [], "duplicates": [], "next_action": ""}
    keys = keys_on_disk()
    by_handle = {}
    for where, token in keys:
        v = validate(token)
        handle = account_handle(token)
        by_handle.setdefault(handle, {"handle": handle, "found_in": [], **v})
        by_handle[handle]["found_in"].append(where)
    report["accounts"] = list(by_handle.values())

    for s in extella_servers():
        headers, stored = server_headers(s["entry"])
        token = str(headers.get("X-Auth-Token", ""))
        row = {"name": s["name"], "scope": s["scope"], "stored": stored,
               "account": account_handle(token) if token else None,
               "agent_header": bool(str(headers.get("X-Agent-Id", "")).strip())}
        row["proven"], row["proof"] = prove_tool_call(headers)
        if not row["proven"] and token:
            v = validate(token)
            row["cause"] = ("key not recognised — create a new token" if v.get("valid") is False
                            else "key is VALID — fix the MCP headers, not the token")
        report["servers"].append(row)

    seen = {}
    for row in report["servers"]:
        if row["account"]:
            seen.setdefault(row["account"], []).append(row["name"])
    report["duplicates"] = [{"account": a, "servers": n} for a, n in seen.items() if len(n) > 1]

    valid = [a for a in report["accounts"] if a.get("valid")]
    proven = [r for r in report["servers"] if r["proven"]]
    if not keys:
        report["next_action"] = NO_KEY
    elif not valid:
        report["next_action"] = ("The key on this computer is not recognised by Extella. "
                                 "Library → System → Tokens: create a new one, save it to "
                                 "~/.extella/api_token.txt (mode 600).")
    elif report["duplicates"]:
        d = report["duplicates"][0]
        report["next_action"] = (f"Two connections to ONE account ({', '.join(d['servers'])}). "
                                 "Keep the one whose key lives in a 0600 file (stored: helper); "
                                 "remove the other with `claude mcp remove <name> -s user` — "
                                 "only after the user agrees.")
    elif not proven:
        report["next_action"] = ("The key is valid, but no connection proves itself. "
                                 "Run `python3 extella_connect.py register`, then restart Claude Code.")
    else:
        report["next_action"] = (f"Connected and proven: {proven[0]['name']}. After a restart, call its "
                                 f"{PROOF_TOOL} tool (no arguments) from this session — that "
                                 "call is the final proof.")
    return report


def connections_of(handle: str) -> list[str]:
    """Names of every Extella server that sends THIS account's key, whatever its name."""
    names = []
    for srv in extella_servers():
        headers, _ = server_headers(srv["entry"])
        sent = str(headers.get("X-Auth-Token", ""))
        if srv["name"] == server_name(handle) or (sent and account_handle(sent) == handle):
            names.append(srv["name"])
    return names


def register() -> dict:
    if sys.platform.startswith("win"):
        return {"status": "error", "message": "Registering on native Windows is not supported yet: "
                "the headers helper is a shell script. Use WSL or macOS/Linux."}
    keys = keys_on_disk()
    if not keys:
        return {"status": "error", "message": NO_KEY}
    where, token = keys[0]
    v = validate(token)
    if not v.get("valid"):
        return {"status": "error", "message": f"Key from {where} is not valid ({v.get('why')})."}
    agent = str(v.get("agent_id") or "")
    if not AGENT_RE.match(agent):
        return {"status": "error", "message": "token/validate returned no usable agent id."}
    handle, h = account_handle(token), home()
    name = server_name(handle)
    # The account is recognised by the KEY a connection sends, not by its name. A
    # name-only check let a legacy `extella` server (key in plain headers) and this
    # registrar's `extella_acct_…` coexist for one account — measured 30.09.2026.
    same_account = connections_of(handle)
    if same_account:
        return {"status": "exists", "server": same_account[0], "servers": same_account,
                "message": ("This account already has a connection (" + ", ".join(same_account) +
                            "); nothing was changed. A second one would duplicate it.")}
    if not shutil.which("claude"):
        return {"status": "error", "message": "The `claude` command is not on PATH."}
    (h / ".extella" / "mcp").mkdir(parents=True, exist_ok=True)
    tf, hf = token_file(handle, h), helper_file(handle, h)
    tf.write_text(token + "\n", encoding="utf-8")
    os.chmod(tf, 0o600)
    hf.write_text(helper_script(handle, agent, h), encoding="utf-8")
    os.chmod(hf, 0o700)
    done = subprocess.run(["claude", "mcp", "add-json", "--scope", "user", name,
                           json.dumps(server_entry(str(hf)))],
                          capture_output=True, text=True, timeout=120)
    if done.returncode != 0:
        return {"status": "error", "message": "claude mcp add-json refused: " +
                (done.stdout + done.stderr).replace(token, "…")[:200]}
    ok, proof = prove_tool_call(json.loads(subprocess.run([str(hf)], capture_output=True,
                                                          text=True).stdout))
    return {"status": "registered" if ok else "registered_unproven", "server": name,
            "account": handle, "agent_id": agent, "proof": proof, "key_from": where,
            "message": f"Restart Claude Code, then call {PROOF_TOOL} of {name} (no arguments)."}


# ── self-test (offline) ────────────────────────────────────────────────────
def selftest() -> int:
    import tempfile
    fails = []
    h = pathlib.Path("/home/x")
    handle = account_handle("00000000-1111-2222-3333-444444444444")
    if not HANDLE_RE.match(handle):
        fails.append("handle has the wrong shape")
    if account_handle("  k-12345678 ") != account_handle("k-12345678"):
        fails.append("handle depends on surrounding spaces")
    script = helper_script(handle, "agent_abcdefgh12", h)
    if "k-12345678" in script or "00000000-1111" in script:
        fails.append("helper carries the key inside itself")
    if f"{h}/.extella/mcp/{handle}.token" not in script:
        fails.append("helper does not read the account's own token file")
    try:
        helper_script(handle, "", h)
        fails.append("helper accepted an empty agent id")
    except ValueError:
        pass
    if server_entry("/abs/x.sh") != {"type": "http", "url": MCP_URL, "headersHelper": "/abs/x.sh"}:
        fails.append("server entry differs from the bridge format")
    ok, why = prove_tool_call({"X-Auth-Token": "k-12345678", "X-Profile-Id": PROFILE})
    if ok or "X-Agent-Id" not in why:
        fails.append("missing X-Agent-Id is not named as the cause before any network call")
    if judge(None)[0] or judge({})[0]:
        fails.append("an unparsed or empty answer counts as proof — the false green of 30.09")
    if judge({"result": {"content": [{"text": "x"}]}})[0]:
        fails.append("an answer without isError=false counts as proof")
    if judge({"result": {"isError": True, "content": [{"text": "dependency 'token'"}]}})[0]:
        fails.append("a refused call counts as proof")
    if not judge({"result": {"isError": False, "content": [{"text": '{"profiles": []}'}]}})[0]:
        fails.append("a valid parsed answer is not accepted")
    # The advice the user acts on must name the proof tool, not the one that overflows.
    src = pathlib.Path(__file__).read_text(encoding="utf-8")
    if any(n in src for n in ("call " + "list_agents", "list_" + "agents tool")):
        fails.append("the next action sends the user to list_agents, which overflows on a large account")
    if PROOF_TOOL == "get_current_profile_and_agent":
        fails.append("the proof tool echoes headers and accepts a wrong key")
    with tempfile.TemporaryDirectory() as tmp:
        old = os.environ.get("HOME")
        os.environ["HOME"] = tmp
        saved_env = os.environ.pop("EXTELLA_API_TOKEN", None)
        try:
            if keys_on_disk():
                fails.append("an empty home reported keys")
            # A legacy server under another name, key in plain headers, same account.
            legacy_key = "legacy-key-12345678"
            (pathlib.Path(tmp) / ".claude.json").write_text(json.dumps({"mcpServers": {
                "extella": {"type": "http", "url": MCP_URL,
                            "headers": {"X-Auth-Token": legacy_key}}}}), encoding="utf-8")
            if connections_of(account_handle(legacy_key)) != ["extella"]:
                fails.append("a legacy connection under another name is not recognised "
                             "as the same account — register would duplicate it")
            if connections_of(account_handle("another-key-12345678")):
                fails.append("another account's key is taken for this one")
            r = {"next_action": NO_KEY} if not keys_on_disk() else doctor()
            if "Tokens" not in r["next_action"] or "chat" not in r["next_action"]:
                fails.append("no-key action does not lead to the Tokens screen")
        finally:
            os.environ["HOME"] = old or ""
            if saved_env is not None:
                os.environ["EXTELLA_API_TOKEN"] = saved_env
    for f in fails:
        print("  ✗ " + f)
    print("SELFTEST: " + ("failures" if fails else "all checks passed"))
    return 1 if fails else 0


if __name__ == "__main__":
    for _stream in (sys.stdout, sys.stderr):
        try:
            _stream.reconfigure(encoding="utf-8", errors="replace")
        except Exception:                                        # noqa: BLE001
            pass
    args = sys.argv[1:]
    if "--selftest" in args:
        sys.exit(selftest())
    out = register() if "register" in args else doctor()
    if "--json" in args:
        print(json.dumps(out, ensure_ascii=False, indent=2))
    else:
        print(json.dumps(out, ensure_ascii=False, indent=2) if "register" in args else
              "\n".join([f"accounts: " + ", ".join(f"{a['handle']} valid={a.get('valid')} "
                                                  f"agent={a.get('agent_id')}" for a in out["accounts"]) or "none",
                         *[f"server {s['name']} ({s['stored']}): "
                           f"{'PROVEN' if s['proven'] else 'NOT proven'} — {s['proof']}"
                           + (f"; {s['cause']}" if s.get('cause') else "") for s in out["servers"]],
                         *[f"DUPLICATE: {', '.join(d['servers'])} → one account" for d in out["duplicates"]],
                         "next: " + out["next_action"]]))
    sys.exit(0)
